FROM amd64/alpine:3.19@sha256:6457d53fb065d6f250e1504b9bc42d5b6c65941d57532c072d929dd0628977d0 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9503
ENTRYPOINT ["/usr/bin/scw_exporter"]
HEALTHCHECK CMD ["/usr/bin/scw_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/scw_exporter /usr/bin/scw_exporter
