# escape=`
FROM microsoft/nanoserver:10.0.14393.2430

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Scaleway Exporter" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 9503
ENTRYPOINT ["c:\\scw_exporter.exe"]

COPY bin/scw_exporter.exe c:\scw_exporter.exe
