FROM amd64/alpine:3.20@sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9503
ENTRYPOINT ["/usr/bin/scw_exporter"]
HEALTHCHECK CMD ["/usr/bin/scw_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/scw_exporter /usr/bin/scw_exporter
