FROM webhippie/alpine:latest-amd64 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Scaleway Exporter" \
  org.opencontainers.image.documentation="https://promhippie.github.io/scw_exporter/" \
  org.opencontainers.image.vendor="Thomas Boerger"

EXPOSE 9503
ENTRYPOINT ["/usr/bin/scw_exporter"]
HEALTHCHECK CMD ["/usr/bin/scw_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/scw_exporter /usr/bin/scw_exporter
