FROM arm32v6/alpine:3.21@sha256:2c2afdf9c980373d45dd1ae735da4a649b6e01dccd126d4028ed68ae9c5ffdbe AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9503
ENTRYPOINT ["/usr/bin/scw_exporter"]
HEALTHCHECK CMD ["/usr/bin/scw_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/scw_exporter /usr/bin/scw_exporter
