FROM arm32v6/alpine:3.19@sha256:b229a85166aadbde58e73e03c5e2b9737fb4642ffb2d98ba453adc90d144c1d8 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9503
ENTRYPOINT ["/usr/bin/scw_exporter"]
HEALTHCHECK CMD ["/usr/bin/scw_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/scw_exporter /usr/bin/scw_exporter
