---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicemonitor.yml
  - service.yml
  - deployment.yml

configMapGenerator:
  - name: scw-exporter
    literals: []

secretGenerator:
  - name: scw-exporter
    literals: []

images:
  - name: scw-exporter
    newName: quay.io/promhippie/scw-exporter
    newTag: latest@sha256:b77c68931deb91830efb5014a09eca7627efa9f42aa6c5a5037d212dbb2489d0

...
